name: Research question
description: Propose a falsifiable research question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: textarea
    id: protocol
    attributes:
      label: Proposed validation protocol
    validations:
      required: true
